name: PHP CodeSniffer on changed files

on:
  pull_request:
    branches: [ trunk ]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          jq 'del(.require, .repositories)' composer.json > composer.dev.json
          rm composer.lock
          COMPOSER=composer.dev.json composer install --no-interaction --prefer-dist --no-progress --no-scripts --ignore-platform-reqs

      - name: Run PHP CodeSniffer
        run: |
          git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} -- '*.php' | xargs -r composer run phpcs
