name: PHP CodeSniffer on changed files

on:
  pull_request:
    branches: [ trunk ]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remove private package
        run: composer remove automattic/newspack-migration-tools --no-update

      - name: Install dependencies using the lock file
        run: composer install

      - name: Run PHP CodeSniffer
        run: |
          git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} -- '*.php' | xargs -r composer run phpcs
