name: PHP CodeSniffer on changed files

on:
  pull_request:
    branches: [ trunk ]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for PHP file changes
        id: check_php_changes
        run: |
          CHANGED_PHP_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} | grep '\.php$' || echo 'no files')
          echo $CHANGED_PHP_FILES
          if [ "$CHANGED_PHP_FILES" = "no files" ]; then
            echo "php_files_changed=false" >> $GITHUB_ENV
          else
            echo "php_files_changed=true" >> $GITHUB_ENV
            CHANGED_PHP_FILES=$(echo "$CHANGED_PHP_FILES" | tr '\n' ' ')
            echo "CHANGED_PHP_FILES=$CHANGED_PHP_FILES" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        if: ${{ env.php_files_changed == 'true' }}
        run: |
          jq 'del(.require, .repositories)' composer.json > composer.dev.json
          rm composer.lock
          COMPOSER=composer.dev.json composer install --no-interaction --prefer-dist --no-progress --no-scripts --ignore-platform-reqs

      - name: Run PHP CodeSniffer on changed files
        if: ${{ env.php_files_changed == 'true' }}
        run: |
          ./vendor/bin/phpcs-changed --git --git-base ${{ github.event.pull_request.base.sha }} ${{ env.CHANGED_PHP_FILES }}