name: Update NMT Dependency

on:
  repository_dispatch:
    types: [update-nmt-dependency]

jobs:
  update-dependency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: trunk

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Composer update NMT package
        run: COMPOSER_NO_INTERACTION=1 composer update automattic/newspack-migration-tools --no-install

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
